import type { ScreenMeta, ScreenRole } from './types';

/** Documented screens from platform-ai/docs/functional/SCREEN-INVENTORY.md */
const GROUP_A: ScreenMeta[] = [
  {
    id: 'auth-welcome',
    docId: 'AUTH-WELCOME',
    route: '/welcome',
    role: 'shared',
    group: 'A',
    frame: 'phone',
    titleEn: 'Welcome',
    titleAr: 'مرحباً',
    descriptionEn: 'Role and language entry — customer, shop owner, staff',
    descriptionAr: 'اختيار الدور واللغة — زبون، متجر، موظف',
    entryPoints: ['app launch', 'sign out'],
    exitPoints: ['AUTH-PHONE', 'AUTH-VENDOR-LOGIN', 'AUTH-STAFF-LOGIN'],
  },
  {
    id: 'auth-phone',
    docId: 'AUTH-PHONE',
    route: '/auth/customer/phone',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Phone entry',
    titleAr: 'رقم الهاتف',
    descriptionEn: 'Collect phone for OTP verification',
    descriptionAr: 'إدخال رقم الهاتف لرمز التحقق',
    exitPoints: ['AUTH-OTP'],
  },
  {
    id: 'auth-otp',
    docId: 'AUTH-OTP',
    route: '/auth/customer/otp',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'OTP verification',
    titleAr: 'رمز التحقق',
    descriptionEn: 'Six-digit code verification',
    descriptionAr: 'التحقق برمز من 6 أرقام',
    exitPoints: ['AUTH-SHOPS', 'BOOK-STOREFRONT'],
  },
  {
    id: 'auth-shops',
    docId: 'AUTH-SHOPS',
    route: '/auth/vendor-picker',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Your shops',
    titleAr: 'متاجرك',
    descriptionEn: 'Linked shops list and selection',
    descriptionAr: 'قائمة المتاجر المرتبطة والاختيار',
    exitPoints: ['BOOK-STOREFRONT', 'AUTH-QR'],
  },
  {
    id: 'auth-qr',
    docId: 'AUTH-QR',
    route: '/qr-scanner',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'QR scanner',
    titleAr: 'مسح QR',
    descriptionEn: 'Link shop via QR scan',
    descriptionAr: 'ربط متجر عبر مسح QR',
    exitPoints: ['AUTH-SHOPS'],
  },
  {
    id: 'book-storefront',
    docId: 'BOOK-STOREFRONT',
    route: '/storefront',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Shop storefront',
    titleAr: 'واجهة المتجر',
    descriptionEn: 'Shop landing and start booking',
    descriptionAr: 'صفحة المتجر وبدء الحجز',
    exitPoints: ['BOOK-STAFF', 'AUTH-SHOPS'],
  },
  {
    id: 'book-staff',
    docId: 'BOOK-STAFF',
    route: '/booking/staff',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Staff selection',
    titleAr: 'اختيار الموظف',
    descriptionEn: 'Choose professional for appointment',
    descriptionAr: 'اختيار الموظف للموعد',
    exitPoints: ['BOOK-SERVICES'],
  },
  {
    id: 'book-services',
    docId: 'BOOK-SERVICES',
    route: '/booking/services',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Service selection',
    titleAr: 'اختيار الخدمة',
    descriptionEn: 'Choose service with duration and price',
    descriptionAr: 'اختيار الخدمة مع المدة والسعر',
    exitPoints: ['BOOK-SLOTS'],
  },
  {
    id: 'book-slots',
    docId: 'BOOK-SLOTS',
    route: '/booking/slots',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Slot picker',
    titleAr: 'اختيار الموعد',
    descriptionEn: 'Date and time slot selection',
    descriptionAr: 'اختيار التاريخ والوقت',
    exitPoints: ['BOOK-DISCOUNT', 'BOOK-CONFIRM'],
  },
  {
    id: 'book-discount',
    docId: 'BOOK-DISCOUNT',
    route: '/booking/discount',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Discount entry',
    titleAr: 'كود الخصم',
    descriptionEn: 'Apply promo code (DISCOUNTS add-on)',
    descriptionAr: 'تطبيق كود الخصم',
    exitPoints: ['BOOK-CONFIRM'],
  },
  {
    id: 'book-confirm',
    docId: 'BOOK-CONFIRM',
    route: '/booking/confirm',
    role: 'customer',
    group: 'A',
    frame: 'phone',
    titleEn: 'Booking confirmation',
    titleAr: 'تأكيد الحجز',
    descriptionEn: 'Summary and create appointment',
    descriptionAr: 'ملخص وإنشاء الموعد',
    exitPoints: ['BOOK-STOREFRONT'],
  },
  {
    id: 'auth-vendor-login',
    docId: 'AUTH-VENDOR-LOGIN',
    route: '/auth/vendor/login',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Vendor login',
    titleAr: 'دخول المتجر',
    descriptionEn: 'Owner email and password sign-in',
    descriptionAr: 'تسجيل دخول المالك',
    exitPoints: ['VEN-DASH'],
  },
  {
    id: 'ven-dash',
    docId: 'VEN-DASH',
    route: '/vendor/dashboard',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Vendor dashboard',
    titleAr: 'لوحة المتجر',
    descriptionEn: "Today's appointments and nav",
    descriptionAr: 'مواعيد اليوم والتنقل',
    exitPoints: ['VEN-STAFF', 'VEN-SERVICES', 'VEN-DISCOUNTS', 'VEN-ADDONS', 'VEN-BRANDING'],
  },
  {
    id: 'ven-staff',
    docId: 'VEN-STAFF',
    route: '/vendor/employees',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Staff management',
    titleAr: 'إدارة الموظفين',
    descriptionEn: 'Roster CRUD',
    descriptionAr: 'إدارة قائمة الموظفين',
  },
  {
    id: 'ven-services',
    docId: 'VEN-SERVICES',
    route: '/vendor/services',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Service catalog',
    titleAr: 'كتalog الخدمات',
    descriptionEn: 'Service catalog management',
    descriptionAr: 'إدارة الخدمات',
  },
  {
    id: 'ven-discounts',
    docId: 'VEN-DISCOUNTS',
    route: '/vendor/discounts',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Discounts',
    titleAr: 'الخصومات',
    descriptionEn: 'Promo code management',
    descriptionAr: 'إدارة أكواد الخصم',
  },
  {
    id: 'ven-addons',
    docId: 'VEN-ADDONS',
    route: '/vendor/addons',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Add-on marketplace',
    titleAr: 'سوق الإضافات',
    descriptionEn: 'Read-only add-on list',
    descriptionAr: 'قائمة الإضافات',
  },
  {
    id: 'ven-branding',
    docId: 'VEN-BRANDING',
    route: '/vendor/branding',
    role: 'vendor',
    group: 'A',
    frame: 'phone',
    titleEn: 'Branding and hours',
    titleAr: 'الهوية وساعات العمل',
    descriptionEn: 'Theme and weekly hours',
    descriptionAr: 'الهوية وساعات العمل',
  },
  {
    id: 'auth-staff-login',
    docId: 'AUTH-STAFF-LOGIN',
    route: '/auth/employee/login',
    role: 'employee',
    group: 'A',
    frame: 'phone',
    titleEn: 'Staff login',
    titleAr: 'دخول الموظف',
    descriptionEn: 'Phone, PIN, and vendor ID',
    descriptionAr: 'هاتف، PIN، معرف المتجر',
    exitPoints: ['EMP-SCHEDULE'],
  },
  {
    id: 'emp-schedule',
    docId: 'EMP-SCHEDULE',
    route: '/employee/schedule',
    role: 'employee',
    group: 'A',
    frame: 'phone',
    titleEn: 'My schedule',
    titleAr: 'جدولي',
    descriptionEn: 'Day schedule and outcome actions',
    descriptionAr: 'جدول اليوم وإجراءات الحالة',
  },
  {
    id: 'adm-login',
    docId: 'ADM-LOGIN',
    route: '/login',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Admin login',
    titleAr: 'دخول المشرف',
    descriptionEn: 'Platform admin authentication',
    descriptionAr: 'مصادقة مشرف المنصة',
    exitPoints: ['ADM-DASH'],
  },
  {
    id: 'adm-dash',
    docId: 'ADM-DASH',
    route: '/',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Platform dashboard',
    titleAr: 'لوحة المنصة',
    descriptionEn: 'Platform metrics home',
    descriptionAr: 'مؤشرات المنصة',
    exitPoints: ['ADM-VENDORS', 'ADM-ONBOARD', 'ADM-ADDONS', 'ADM-AUDIT'],
  },
  {
    id: 'adm-vendors',
    docId: 'ADM-VENDORS',
    route: '/vendors',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Vendor list',
    titleAr: 'قائمة المتاجر',
    descriptionEn: 'Searchable vendor table',
    descriptionAr: 'جدول المتاجر',
    exitPoints: ['ADM-VENDOR', 'ADM-ONBOARD'],
  },
  {
    id: 'adm-onboard',
    docId: 'ADM-ONBOARD',
    route: '/vendors/new',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Onboard vendor',
    titleAr: 'إضافة متجر',
    descriptionEn: 'Create vendor and owner credentials',
    descriptionAr: 'إنشاء متجر وبيانات المالك',
    exitPoints: ['ADM-VENDOR'],
  },
  {
    id: 'adm-vendor',
    docId: 'ADM-VENDOR',
    route: '/vendors/:id',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Vendor detail',
    titleAr: 'تفاصيل المتجر',
    descriptionEn: 'Inspect and admin operations',
    descriptionAr: 'عرض وعمليات الإدارة',
  },
  {
    id: 'adm-addons',
    docId: 'ADM-ADDONS',
    route: '/addons',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Add-on catalog',
    titleAr: 'كتalog الإضافات',
    descriptionEn: 'Platform add-on catalog',
    descriptionAr: 'كتalog إضافات المنصة',
  },
  {
    id: 'adm-audit',
    docId: 'ADM-AUDIT',
    route: '/audit',
    role: 'super-admin',
    group: 'A',
    frame: 'tablet',
    titleEn: 'Audit log',
    titleAr: 'سجل التدقيق',
    descriptionEn: 'Audit log viewer',
    descriptionAr: 'عارض سجل التدقيق',
  },
];

export const SCREEN_REGISTRY: ScreenMeta[] = [...GROUP_A];

export const DOCUMENTED_SCREEN_IDS = GROUP_A.map((s) => s.docId!).filter(Boolean);

export function getScreenById(id: string): ScreenMeta | undefined {
  return SCREEN_REGISTRY.find((s) => s.id === id || s.docId === id);
}

export function getScreensByRole(role: ScreenRole): ScreenMeta[] {
  return SCREEN_REGISTRY.filter((s) => s.role === role || (role === 'shared' && s.role === 'shared'));
}

export function getScreensByGroup(group: 'A'): ScreenMeta[] {
  return SCREEN_REGISTRY.filter((s) => s.group === group);
}

export const ROLE_ORDER: ScreenRole[] = ['shared', 'customer', 'vendor', 'employee', 'super-admin'];

export const ROLE_LABELS: Record<ScreenRole, { en: string; ar: string }> = {
  shared: { en: 'Shared', ar: 'مشترك' },
  customer: { en: 'Customer', ar: 'زبون' },
  vendor: { en: 'Vendor', ar: 'متجر' },
  employee: { en: 'Employee', ar: 'موظف' },
  'super-admin': { en: 'Super Admin', ar: 'مشرف المنصة' },
};
